# action.yml
name: 'Run JS in Docker'
description: 'Print out the data in POST payload in Docker'
inputs:
  data:
    description: 'Test data json'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.data }}