name: Log Payload

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Payload owner'
        required: true
        default: 'Pixie the Cat'
      data:
        description: 'Test data'
        required: true
        default: '{"scenario": "fake_data"}'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Save 'data' payload to file system
        run: |
          echo ${{ github.event.inputs.data }} > payload.json
          cat payload.json
      - name: Echo the payload in terminal
        run: |
            echo "Hello, this is ${{ github.event.inputs.name }}!"
            echo "${{ github.event.inputs.data }}"
      - name: Run JS script in Docker
        run: |
            docker build -t say_hello .
            docker run say_hello node index.js
