name: Log Payload

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Save payload to file system
        run: |
          echo ${{ github.event.inputs.name }} > payload.json
          cat payload.json
      - name: Echo the payload in terminal
        run: |
            echo "Hello ${{ github.event.inputs.name }}!"
            echo "- in ${{ github.event.inputs.home }}!"
      - name: Run JS script in Docker
        run: |
            docker build -t say_hello .
            docker run say_hello node index.js
