name: Log Payload with Repo Dispatch

on:
  repository_dispatch:
    types: [post_request, test_event]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo github.event.types
        run: |
            echo ${{ github.event.event_type }}
      - name: Echo the payload in terminal
        run: |
            echo "Hello, this is payload: ${{ github.event.client_payload }}"
            echo "Hello, this is the scenario: ${{ github.event.client_payload.scenario }}"
            echo "Here's an Ask: ${{ github.event.client_payload.ask0001 }}"
      - name: Use custom action to run Docker
        uses: ./.github/run_in_docker
        # with:
          # this line kept getting "A mapping was not expected" error (* See comments at bottom)
          # testdata: ${{ github.event.client_payload }} 

####################################################
# Testing whether I can have multiple distinct workflow logic that depends on `types`
### DIDN'T WORK
# on:
#   repository_dispatch:
#     types: test_event

# jobs:
#   say_hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Echo the payload in terminal
#         run: |
#             echo "Hello, this is the test_event"
#             echo "Hello, this is payload: ${{ github.event.client_payload }}"
            
# * Turned out for my use I didn't need to pass any input params. I just needed to access
# payload inside `context`. So I ended up just not using the `with` key and its mapping
# and didn't bother looking into the annoying "mapping not expected" error ✌️.